### ISSUE TITLE
Leistungsdateneingabe durch KL (Diskussion)

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Prognos2#2]
Folgende Diskussion steht noch aus:

Sollte es bei den Einstellungen die Möglichkeit geben, dass der KL nicht nur die Prognosen bearbeiten kann sondern, auch die Leistungsdaten. Diese Bearbeitungsmöglichkeit gibt es nur für den SchILD-Admin-

Meine Meinung: 
Das würde die Gefahr mit sich bringen, dass hier Noten geändert werden, um mal zu schauen, wie dann die Prognose aussieht und diese Änderungen dann versehentlich nicht rückgängig gemacht werden. 
Wurde diese Option mal gewünscht?

**Comment by Blomeyer** [comment]
Haben wir das nicht in der Leistungsdatenverwaltung: "Bei Klassenlehreren komplette Klasse ausgeben"
Beim alten Prognos war das auch möglich - glaube ich ?!

In der Sache sehe ich das wie Frau Schüller.
Wird eigentlich in SchIlD3 bzw. SVWS-Server bei jeder Note abgespeichert, wer und wann die Note zuletzt gespeicheert hat?

**Comment by FPfotenhauer** [comment]
Für mich ist Prognos kein Tool um Noten einzugeben.

> Wird eigentlich in SchIlD3 bzw. SVWS-Server bei jeder Note abgespeichert, wer und wann die Note zuletzt gespeicheert hat?

Es wird über Trigger ein Zeitstempel der letzen Änderung gesetzt.

**Comment by AnneSchueller** [comment]
Ich schließe das Issue mit dem Fazit: Keine Eingaben vor Noten für Klassenlehrer in PM2
